# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [172]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [173]:
# Loading data using pandas
data = pd.read_csv("AviationData.csv", encoding="latin-1")
data

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [174]:
# Getting the NaNs and data types
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

Oberversation: the data contains 5 numeric and 26 categorical columns

In [175]:
# Summary statistics
data.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

In [176]:
data.describe(include="object").T

                       count unique             top   freq
Event.Id               88889  87951  20001212X19172      3
Investigation.Type     88889      2        Accident  85015
Accident.Number        88889  88863      CEN22LA149      2
Event.Date             88889  14782      1984-06-30     25
Location               88837  27758   ANCHORAGE, AK    434
Country                88663    219   United States  82248
Latitude               34382  25592         332739N     19
Longitude              34373  27156        0112457W     24
Airport.Code           50132  10374            NONE   1488
Airport.Name           52704  24870         Private    240
Injury.Severity        87889    109       Non-Fatal  67357
Aircraft.damage        85695      4     Substantial  64148
Aircraft.Category      32287     15        Airplane  27617
Registration.Number    87507  79104            NONE    344
Make                   88826   8237          Cessna  22227
Model                  88797  12318             152   2367
Amateur.Built          88787      2              No  80312
Engine.Type            81793     12   Reciprocating  69530
FAR.Description        32023     31             091  18221
Schedule               12582      3            NSCH   4474
Purpose.of.flight      82697     26        Personal  49448
Air.carrier            16648  13590           Pilot    258
Weather.Condition      84397      4             VMC  77303
Broad.phase.of.flight  61724     12         Landing  15428
Report.Status          82505  17074  Probable Cause  61754
Publication.Date       75118   2924      25-09-2020  17019

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [177]:
# looking at category of aircrafts
data["Aircraft.Category"].value_counts()

Aircraft.Category
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

In [178]:
#Filtering airplanes
airplanes = data[data['Aircraft.Category']=='Airplane']
airplanes['Aircraft.Category'].value_counts()

Aircraft.Category
Airplane    27617
Name: count, dtype: int64

In [179]:
airplanes["Amateur.Built"].value_counts()

Amateur.Built
No     24417
Yes     3183
Name: count, dtype: int64

In [180]:
#Filtering out planes by make
professional = airplanes[airplanes['Amateur.Built']=='No']
professional['Amateur.Built'].value_counts()

Amateur.Built
No    24417
Name: count, dtype: int64

In [181]:
professional["Event.Date"].value_counts()

Event.Date
1982-05-16    22
1982-06-19    20
1982-07-09    19
1982-05-01    18
1982-07-31    17
              ..
2009-03-13     1
2009-03-16     1
2009-03-24     1
2009-03-25     1
2022-12-26     1
Name: count, Length: 7134, dtype: int64

In [182]:
# Filtering out events older than 40 years
event_date = professional[professional['Event.Date']>='1983']
event_date['Event.Date'].value_counts()

Event.Date
2011-07-23    15
2018-09-01    14
2012-08-31    14
2011-06-18    13
2008-06-28    13
              ..
2007-03-30     1
2018-12-27     1
2018-12-26     1
2018-12-25     1
2022-12-26     1
Name: count, Length: 6769, dtype: int64

In [183]:
event_date

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
4149,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,Unknown,NaN,NaN,NaN,NaN,588.0,VMC,Standing,Probable Cause,04-12-2014
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,"Singapore Airlines, Ltd.",NaN,NaN,NaN,588.0,VMC,Taxi,Probable Cause,04-12-2014
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,1.0,NaN,NaN,IMC,Cruise,Probable Cause,02-05-2011
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,Skydiving,NaN,1.0,NaN,NaN,4.0,VMC,Standing,Probable Cause,17-10-2016
5957,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,Unknown,NaN,NaN,NaN,NaN,289.0,VMC,Cruise,Probable Cause,01-02-2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,Personal,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,Personal,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [184]:
#Removing null values
event_date['Total.Fatal.Injuries']= event_date['Total.Fatal.Injuries'].fillna(0)
event_date['Number.of.Engines']=  event_date['Number.of.Engines'].fillna(0)
event_date['Total.Minor.Injuries']= event_date['Total.Minor.Injuries'].fillna(0)
event_date['Total.Uninjured']= event_date['Total.Uninjured'].fillna(0)
event_date['Total.Serious.Injuries']= event_date['Total.Serious.Injuries'].fillna(0)
event_date['Aircraft.damage'] = event_date['Aircraft.damage'].fillna('unknown')

In [185]:
#Finding the total passengers
event_date['Total.Passengers'] = (
    event_date['Total.Fatal.Injuries'] +
    event_date['Total.Serious.Injuries'] +
    event_date['Total.Minor.Injuries'] +
    event_date['Total.Uninjured'])

In [186]:
#Finding the  % of total fatal injuries
event_date['% Fatal.Injuries'] =(event_date['Total.Fatal.Injuries']/ event_date['Total.Passengers']) * 100
event_date['% Serious.Injuries'] =(event_date['Total.Serious.Injuries']/event_date['Total.Passengers']) *100
event_date['% Minor.Injuries'] =(event_date['Total.Minor.Injuries']/event_date['Total.Passengers']) *100
event_date['% Serious/Fatal.Injured'] =((event_date['Total.Fatal.Injuries']+event_date['Total.Serious.Injuries'])/event_date['Total.Passengers']) * 100
event_date

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Total.Passengers,% Fatal.Injuries,% Serious.Injuries,% Minor.Injuries,% Serious/Fatal.Injured
4149,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,588.0,VMC,Standing,Probable Cause,04-12-2014,588.0,0.0,0.0,0.0,0.0
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,588.0,VMC,Taxi,Probable Cause,04-12-2014,588.0,0.0,0.0,0.0,0.0
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,0.0,IMC,Cruise,Probable Cause,02-05-2011,2.0,50.0,50.0,0.0,100.0
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,4.0,VMC,Standing,Probable Cause,17-10-2016,5.0,20.0,0.0,0.0,20.0
5957,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,289.0,VMC,Cruise,Probable Cause,01-02-2016,289.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,1.0,NaN,NaN,NaN,14-12-2022,1.0,0.0,0.0,0.0,0.0
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,1.0,VMC,NaN,NaN,27-12-2022,1.0,0.0,0.0,0.0,0.0
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,1.0,NaN,NaN,NaN,19-12-2022,1.0,0.0,0.0,0.0,0.0
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,0.0,VMC,NaN,NaN,23-12-2022,1.0,0.0,100.0,0.0,100.0
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,1.0,VMC,NaN,NaN,27-12-2022,1.0,0.0,0.0,0.0,0.0

In [187]:
event_date.describe().T

,count,mean,std,min,25%,50%,75%,max
Number.of.Engines,21447.0,1.038280,0.555154,0.0,1.0,1.0,1.0,8.0
Total.Fatal.Injuries,21447.0,0.645871,6.326507,0.0,0.0,0.0,0.0,295.0
Total.Serious.Injuries,21447.0,0.280692,2.218737,0.0,0.0,0.0,0.0,161.0
Total.Minor.Injuries,21447.0,0.203245,1.647516,0.0,0.0,0.0,0.0,200.0
Total.Uninjured,21447.0,7.462489,35.064707,0.0,0.0,1.0,2.0,588.0
Total.Passengers,21447.0,8.592297,35.910084,0.0,1.0,2.0,2.0,588.0
% Fatal.Injuries,20543.0,17.254178,36.791339,0.0,0.0,0.0,0.0,100.0
% Serious.Injuries,20543.0,11.142949,29.385407,0.0,0.0,0.0,0.0,100.0
% Minor.Injuries,20543.0,8.651242,25.770427,0.0,0.0,0.0,0.0,100.0
% Serious/Fatal.Injured,20543.0,28.397126,43.170351,0.0,0.0,0.0,80.0,100.0

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [188]:
event_date.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21447 entries, 4149 to 88886
Data columns (total 36 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Event.Id                 21447 non-null  object
 1   Investigation.Type       21447 non-null  object
 2   Accident.Number          21447 non-null  object
 3   Event.Date               21447 non-null  object
 4   Location                 21441 non-null  object
 5   Country                  21446 non-null  object
 6   Latitude                 19169 non-null  object
 7   Longitude                19163 non-null  object
 8   Airport.Code             13983 non-null  object
 9   Airport.Name             14070 non-null  object
 10  Injury.Severity          20634 non-null  object
 11  Aircraft.damage          21447 non-null  object
 12  Aircraft.Category        21447 non-null  object
 13  Registration.Number      21241 non-null  object
 14  Make                     21444 non-null  object
 15  Model                    21429 non-null  object
 16  Amateur.Built            21447 non-null  object
 17  Number.of.Engines        21447 non-null  float64
 18  Engine.Type              17491 non-null  object
 19  FAR.Description          20967 non-null  object
 20  Schedule                 2521 non-null   object
 21  Purpose.of.flight        17767 non-null  object
 22  Air.carrier              10162 non-null  object
 23  Total.Fatal.Injuries     21447 non-null  float64
 24  Total.Serious.Injuries   21447 non-null  float64
 25  Total.Minor.Injuries     21447 non-null  float64
 26  Total.Uninjured          21447 non-null  float64
 27  Weather.Condition        18468 non-null  object
 28  Broad.phase.of.flight    2828 non-null   object
 29  Report.Status            16784 non-null  object
 30  Publication.Date         20490 non-null  object
 31  Total.Passengers         21447 non-null  float64
 32  % Fatal.Injuries         20543 non-null  float64
 33  % Serious.Injuries       20543 non-null  float64
 34  % Minor.Injuries         20543 non-null  float64
 35  % Serious/Fatal.Injured  20543 non-null  float64
dtypes: float64(10), object(26)
memory usage: 6.1+ MB

In [189]:
event_date['Aircraft.damage'].value_counts()

Aircraft.damage
Substantial    16990
Destroyed       2316
unknown         1227
Minor            817
Unknown           97
Name: count, dtype: int64

In [190]:
# Checking aircraft damage
event_date['aircraft.destroyed'] = event_date['Aircraft.damage']==('Destroyed')
event_date['aircraft.destroyed'].value_counts()

aircraft.destroyed
False    19131
True      2316
Name: count, dtype: int64

In [191]:
event_date

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Total.Passengers,% Fatal.Injuries,% Serious.Injuries,% Minor.Injuries,% Serious/Fatal.Injured,aircraft.destroyed
4149,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,VMC,Standing,Probable Cause,04-12-2014,588.0,0.0,0.0,0.0,0.0,False
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,VMC,Taxi,Probable Cause,04-12-2014,588.0,0.0,0.0,0.0,0.0,False
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,IMC,Cruise,Probable Cause,02-05-2011,2.0,50.0,50.0,0.0,100.0,True
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,VMC,Standing,Probable Cause,17-10-2016,5.0,20.0,0.0,0.0,20.0,False
5957,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,VMC,Cruise,Probable Cause,01-02-2016,289.0,0.0,0.0,0.0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,NaN,NaN,14-12-2022,1.0,0.0,0.0,0.0,0.0,False
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,VMC,NaN,NaN,27-12-2022,1.0,0.0,0.0,0.0,0.0,False
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,NaN,NaN,NaN,19-12-2022,1.0,0.0,0.0,0.0,0.0,False
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,VMC,NaN,NaN,23-12-2022,1.0,0.0,100.0,0.0,100.0,False
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,VMC,NaN,NaN,27-12-2022,1.0,0.0,0.0,0.0,0.0,False

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

         Cleaning Tasks
~Standardize text (lowercase → title case)
~Strip whitespace
~Normalize manufacturer names
~Handle missing values
~Filter out rare manufacturers (threshold ≥ 50 records)

In [192]:
event_date['Make'].value_counts()

Make
CESSNA                          4867
PIPER                           2803
Cessna                          2279
Piper                           1186
BOEING                          1037
                                ...
T BIRD GOLDEN CIRCLE AIR INC       1
TIGER AIRCRAFT LLC                 1
Beechcraft Corporation             1
Hawker Beech                       1
ORLICAN S R O                      1
Name: count, Length: 1332, dtype: int64

In [193]:
#Standardizing text
event_date['Make'] = event_date['Make'].str.strip().str.lower()

In [194]:
#Removing NaNs
event_date = event_date.dropna(subset=['Make'])

In [195]:
# Normalizing manufacturers names for better plotting and visualization
make_mapping = {
    'cirrus design corp': 'cirrus',
    'air tractor inc': 'air tractor',     
    'grumman acft eng cor-schweizer': 'grumman',}
event_date['Make'] = event_date['Make'].replace(make_mapping)  # Add mapping to the make column

In [196]:
# Filtering out rare manufacturers
make_counts = event_date['Make'].value_counts()
valid_makes = make_counts[make_counts >= 50].index

event_date = event_date[event_date['Make'].isin(valid_makes)]

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [197]:
event_date

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Total.Passengers,% Fatal.Injuries,% Serious.Injuries,% Minor.Injuries,% Serious/Fatal.Injured,aircraft.destroyed
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,VMC,Taxi,Probable Cause,04-12-2014,588.0,0.0,0.0,0.0,0.0,False
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,IMC,Cruise,Probable Cause,02-05-2011,2.0,50.0,50.0,0.0,100.0,True
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,VMC,Standing,Probable Cause,17-10-2016,5.0,20.0,0.0,0.0,20.0,False
6760,20001214X45013,Incident,CHI84IA041,1983-11-08,"CHICAGO, IL",United States,NaN,NaN,ORD,O'HARE,...,VMC,Taxi,Probable Cause,11-06-2018,100.0,0.0,0.0,0.0,0.0,False
6806,20001214X45188,Accident,NYC84LA028,1983-11-13,"MARTHA'S VINEYARD, MA",United States,NaN,NaN,NaN,NaN,...,VMC,Climb,Probable Cause,05-05-2011,1.0,0.0,0.0,0.0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88865,20221212106444,Accident,ERA23LA085,2022-12-12,"Knoxville, TN",United States,355745N,0835218W,DKX,KNOXVILLE DOWNTOWN ISLAND,...,VMC,NaN,NaN,15-12-2022,1.0,0.0,0.0,0.0,0.0,False
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,NaN,NaN,14-12-2022,1.0,0.0,0.0,0.0,0.0,False
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,VMC,NaN,NaN,27-12-2022,1.0,0.0,0.0,0.0,0.0,False
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,VMC,NaN,NaN,23-12-2022,1.0,0.0,100.0,0.0,100.0,False
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,VMC,NaN,NaN,27-12-2022,1.0,0.0,0.0,0.0,0.0,False

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized